### ISSUE TITLE
Build times increasing with each run

### ISSUE THREAD

**Issue by alastairrmcneill** [cedvdb/action-flutter-build-ios#1]
Heya! 

This workflow is super helpful, thanks! I have it working and correctly creating a signed .ipa file, which is great!

However, I have been testing my workflow and I've run it a few times in a row with the only changes between each run being changing the names of jobs and the build number in pubspec.yaml. Over these multiple runs I've seen the build and archive steps take increasingly long amounts of times. 

<img width="186" alt="Screenshot 2024-04-09 at 21 08 46" src="https://github.com/cedvdb/action-flutter-build-ios/assets/52216324/5aa33343-b019-4a56-b27a-f958b327e168">

It makes sense that the build step and the archive steps are the longest but my question is why? Is there anything I can do to reduce the build times? 

For reference, locally it usually takes ~5 mins to the build and signing, but its been taking upwards of 30 minutes for some of my workflows to execute the same steps. I'd expect the workflow to be slightly slower but not that much slower

**Comment by cedvdb** [comment]
11 minutes seems fine. The fact that it is increasing is worrying though. Please report here if it keeps increasing. I do not have the time to look into this.

**Comment by alastairrmcneill** [comment]
Ah yeah, sorry I forgot about this. 

When I posted I was carrying out many runs because I was testing my pipelines, whereas now that they work I have been running them much less. 

I've been getting a much more consistent time recently of around 20 minutes which seems good. 

So yeah not sure if it was something about running many back to back or something totally unrelated but I don't have this issue at the moment so we can probably close this one
